name: "Continuous Integration"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "migrations/"
      - "*.txt"
      - "*.md"

  pull_request:
    branches: [main]
    paths-ignore:
      - "migrations/"
      - "*.txt"
      - "*.md"

jobs:
  tests:
    name: Run unittests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up Python and Required packages
        uses: ./.github/actions/setup-python/action.yml
        with:
          python-version: "3.10"
          requirements-file: "requirements.txt"

      - name: Run unittests
        run: |
          . venv/bin/activate
          pytest

  test-coverage:
    name: codecov-test_coverage
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up Python and Required dependencies
        uses: ./.github/actions/setup-python/action.yml
        with:
          python-version: "3.10"
          requirements-file: "requirements.txt"

      - name: Run tests with coverage
        run: |
          . venv/bin/activate
          pytest --cov=test

      - name: Upload coverage to Codecov
        run: |
          . venv/bin/activate
          codecov
