name: "Continuous Integration"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "migrations/"
      - "*.txt"
      - "*.md"

  pull_request:
    branches: [main]
    paths-ignore:
      - "migrations/"
      - "*.txt"
      - "*.md"

jobs:
  tests:
    name: Run unittests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up Python and Required packages
        uses: ./.github/actions/setup-python
        with:
          python-version: "3.10"
          requirements-file: "requirements.txt"

      - name: Run unittests
        run: |
          . venv/bin/activate
          pytest

  test-coverage:
    name: codecov-test_coverage
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up Python and Required dependencies
        uses: ./.github/actions/setup-python
        with:
          python-version: "3.10"
          requirements-file: "requirements.txt"

      - name: Run tests with coverage
        run: |
          . venv/bin/activate
          pytest --cov=App --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  Build_Publish:
    name: Push Docker image to Docker Hub, GHCR and ECR
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to Github Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_OICD_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract metadata (tags, labels) for Docker (Docker Hub, GHCR and ECR)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            merch7x/flask-blog
            ghcr.io/$${{ github.repository_owner }}/dev
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/flask-blog
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
